### Cadastro de novo usuário
POST https://localhost:7162/api/user/CreateUser
Content-Type: application/json

{
  "name": "Novo Usuário",
  "email": "novo@empresa.com",
  "password": "Senha@123"
}

### Login
POST https://localhost:7162/api/user/login
Content-Type: application/json

{
  "email": "novo@empresa.com",
  "password": "Senha@123"
}

### Cadastrar jogo

POST https://localhost:7162/api/Admin/CreateGame
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibm92b0BlbXByZXNhLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQ4NTUwMzM2LCJpc3MiOiJTdWFBcHBGaWFwIn0._Ky19a4vI8ER1TwL3-TUIgDND3H58KoBlNfX1DBpBAo
Content-Type: application/json

{
  "name": "GTA VI",
  "price": "700.76",
  "gender": "Ação"
}

### Atualizar perfil de usuário

POST https://localhost:7162/api/Admin/UpdateUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibm92b0BlbXByZXNhLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQ4NTU0NjM0LCJpc3MiOiJTdWFBcHBGaWFwIn0.9UqDTQ-BCY5lk3mtFjg4kH7Veid-lDA7SF93ReERln4
Content-Type: application/json

{
  "name": "userTeste",
  "id": 1
}


### Endpoint protegido, apenas admin.
GET https://localhost:7162/api/User
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibm92b0BlbXByZXNhLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQ4NTMyMzQ5LCJpc3MiOiJTdWFBcHBGaWFwIn0.JPJsYZXqcdwBgdlj7MkgciuUT-r2NpsQo-bGAXhvgUs